// src/patterns/menu-button/MenuButton.svelte
<script lang="ts">
  import { onDestroy, tick } from 'svelte';

  export interface MenuItem {
    id: string;
    label: string;
    disabled?: boolean;
  }

  interface MenuButtonProps {
    items: MenuItem[];
    label: string;
    defaultOpen?: boolean;
    onItemSelect?: (itemId: string) => void;
    class?: string;
  }

  let {
    items = [],
    label,
    defaultOpen = false,
    onItemSelect = () => {},
    class: className = '',
    ...restProps
  }: MenuButtonProps = $props();

  // State - capture defaultOpen value to avoid reactivity warning
  const initialOpen = defaultOpen;
  let isOpen = $state(initialOpen);
  let focusedIndex = $state(-1);
  // Generate ID immediately for SSR-safe aria-controls/aria-labelledby
  const instanceId = `menu-button-${Math.random().toString(36).slice(2, 11)}`;
  let typeAheadBuffer = $state('');
  let typeAheadTimeoutId: number | null = null;
  const typeAheadTimeout = 500;

  // Refs
  let containerElement: HTMLDivElement;
  let buttonElement: HTMLButtonElement;
  let menuItemRefs = new Map<string, HTMLLIElement>();

  // Derived
  let availableItems = $derived(items.filter((item) => !item.disabled));

  // Map of item id to index in availableItems for O(1) lookup
  let availableIndexMap = $derived.by(() => {
    const map = new Map<string, number>();
    availableItems.forEach(({ id }, index) => map.set(id, index));
    return map;
  });

  let buttonId = $derived(`${instanceId}-button`);
  let menuId = $derived(`${instanceId}-menu`);

  onDestroy(() => {
    if (typeAheadTimeoutId !== null) {
      clearTimeout(typeAheadTimeoutId);
    }
    if (typeof document !== 'undefined') {
      document.removeEventListener('mousedown', handleClickOutside);
    }
  });

  // Focus effect - explicitly track dependencies with stale check
  $effect(() => {
    const open = isOpen;
    const index = focusedIndex;
    const items = availableItems;

    if (open && index >= 0) {
      const targetItem = items[index];
      if (targetItem) {
        const targetId = targetItem.id;
        tick().then(() => {
          // Guard against stale focus: check menu is still open
          if (isOpen && focusedIndex >= 0) {
            menuItemRefs.get(targetId)?.focus();
          }
        });
      }
    }
  });

  // Click outside effect (browser-only)
  $effect(() => {
    if (typeof document === 'undefined') return;

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    } else {
      document.removeEventListener('mousedown', handleClickOutside);
    }
  });

  // Action to track menu item refs
  function trackItemRef(node: HTMLLIElement, itemId: string) {
    menuItemRefs.set(itemId, node);
    return {
      destroy() {
        menuItemRefs.delete(itemId);
      },
    };
  }

  function getTabIndex(item: MenuItem): number {
    if (item.disabled) return -1;
    const availableIndex = availableIndexMap.get(item.id) ?? -1;
    return availableIndex === focusedIndex ? 0 : -1;
  }

  function closeMenu() {
    isOpen = false;
    focusedIndex = -1;
    // Clear type-ahead state
    typeAheadBuffer = '';
    if (typeAheadTimeoutId !== null) {
      clearTimeout(typeAheadTimeoutId);
      typeAheadTimeoutId = null;
    }
  }

  function openMenu(focusPosition: 'first' | 'last') {
    if (availableItems.length === 0) {
      isOpen = true;
      return;
    }

    isOpen = true;
    const targetIndex = focusPosition === 'first' ? 0 : availableItems.length - 1;
    focusedIndex = targetIndex;
  }

  function toggleMenu() {
    if (isOpen) {
      closeMenu();
    } else {
      openMenu('first');
    }
  }

  function handleClickOutside(event: MouseEvent) {
    if (containerElement && !containerElement.contains(event.target as Node)) {
      closeMenu();
    }
  }

  async function handleItemClick(item: MenuItem) {
    if (item.disabled) return;
    onItemSelect(item.id);
    closeMenu();
    await tick();
    buttonElement?.focus();
  }

  function handleItemFocus(item: MenuItem) {
    if (item.disabled) return;
    const availableIndex = availableIndexMap.get(item.id) ?? -1;
    if (availableIndex >= 0) {
      focusedIndex = availableIndex;
    }
  }

  function handleButtonKeyDown(event: KeyboardEvent) {
    switch (event.key) {
      case 'Enter':
      case ' ':
        event.preventDefault();
        openMenu('first');
        break;
      case 'ArrowDown':
        event.preventDefault();
        openMenu('first');
        break;
      case 'ArrowUp':
        event.preventDefault();
        openMenu('last');
        break;
    }
  }

  function handleTypeAhead(char: string) {
    if (availableItems.length === 0) return;

    if (typeAheadTimeoutId !== null) {
      clearTimeout(typeAheadTimeoutId);
    }

    typeAheadBuffer += char.toLowerCase();

    const buffer = typeAheadBuffer;
    const isSameChar = buffer.length > 1 && buffer.split('').every((c) => c === buffer[0]);

    let startIndex: number;
    let searchStr: string;

    if (isSameChar) {
      typeAheadBuffer = buffer[0];
      searchStr = buffer[0];
      startIndex = focusedIndex >= 0 ? (focusedIndex + 1) % availableItems.length : 0;
    } else if (buffer.length === 1) {
      searchStr = buffer;
      startIndex = focusedIndex >= 0 ? (focusedIndex + 1) % availableItems.length : 0;
    } else {
      searchStr = buffer;
      startIndex = focusedIndex >= 0 ? focusedIndex : 0;
    }

    for (let i = 0; i < availableItems.length; i++) {
      const index = (startIndex + i) % availableItems.length;
      const option = availableItems[index];
      if (option.label.toLowerCase().startsWith(searchStr)) {
        focusedIndex = index;
        break;
      }
    }

    typeAheadTimeoutId = window.setTimeout(() => {
      typeAheadBuffer = '';
      typeAheadTimeoutId = null;
    }, typeAheadTimeout);
  }

  async function handleMenuKeyDown(event: KeyboardEvent, item: MenuItem) {
    const itemsLength = availableItems.length;

    // Guard: no available items
    if (itemsLength === 0) {
      if (event.key === 'Escape') {
        event.preventDefault();
        closeMenu();
        await tick();
        buttonElement?.focus();
      }
      return;
    }

    const currentIndex = availableIndexMap.get(item.id) ?? -1;

    // Guard: disabled item received focus
    if (currentIndex < 0) {
      if (event.key === 'Escape') {
        event.preventDefault();
        closeMenu();
        await tick();
        buttonElement?.focus();
      }
      return;
    }

    switch (event.key) {
      case 'ArrowDown': {
        event.preventDefault();
        const nextIndex = (currentIndex + 1) % itemsLength;
        focusedIndex = nextIndex;
        break;
      }
      case 'ArrowUp': {
        event.preventDefault();
        const prevIndex = currentIndex === 0 ? itemsLength - 1 : currentIndex - 1;
        focusedIndex = prevIndex;
        break;
      }
      case 'Home': {
        event.preventDefault();
        focusedIndex = 0;
        break;
      }
      case 'End': {
        event.preventDefault();
        focusedIndex = itemsLength - 1;
        break;
      }
      case 'Escape': {
        event.preventDefault();
        closeMenu();
        await tick();
        buttonElement?.focus();
        break;
      }
      case 'Tab': {
        closeMenu();
        break;
      }
      case 'Enter':
      case ' ': {
        event.preventDefault();
        if (!item.disabled) {
          onItemSelect(item.id);
          closeMenu();
          await tick();
          buttonElement?.focus();
        }
        break;
      }
      default: {
        // Type-ahead: single printable character
        const { key, ctrlKey, metaKey, altKey } = event;
        if (key.length === 1 && !ctrlKey && !metaKey && !altKey) {
          event.preventDefault();
          handleTypeAhead(key);
        }
      }
    }
  }
</script>

<div bind:this={containerElement} class="apg-menu-button {className}">
  <button
    bind:this={buttonElement}
    id={buttonId}
    type="button"
    class="apg-menu-button-trigger"
    aria-haspopup="menu"
    aria-expanded={isOpen}
    aria-controls={menuId}
    onclick={toggleMenu}
    onkeydown={handleButtonKeyDown}
    {...restProps}
  >
    {label}
  </button>
  <ul
    id={menuId}
    role="menu"
    aria-labelledby={buttonId}
    class="apg-menu-button-menu"
    hidden={!isOpen ? true : undefined}
    inert={!isOpen ? true : undefined}
  >
    {#each items as item (item.id)}
      <li
        use:trackItemRef={item.id}
        role="menuitem"
        tabindex={getTabIndex(item)}
        aria-disabled={item.disabled || undefined}
        class="apg-menu-button-item"
        onclick={() => handleItemClick(item)}
        onkeydown={(e) => handleMenuKeyDown(e, item)}
        onfocus={() => handleItemFocus(item)}
      >
        {item.label}
      </li>
    {/each}
  </ul>
</div>

// src/patterns/menu-button/MenuButton.vue
<template>
  <div ref="containerRef" :class="`apg-menu-button ${className}`.trim()">
    <button
      ref="buttonRef"
      :id="buttonId"
      type="button"
      class="apg-menu-button-trigger"
      aria-haspopup="menu"
      :aria-expanded="isOpen"
      :aria-controls="menuId"
      v-bind="$attrs"
      @click="toggleMenu"
      @keydown="handleButtonKeyDown"
    >
      {{ label }}
    </button>
    <ul
      :id="menuId"
      role="menu"
      :aria-labelledby="buttonId"
      class="apg-menu-button-menu"
      :hidden="!isOpen || undefined"
      :inert="!isOpen || undefined"
    >
      <li
        v-for="item in items"
        :key="item.id"
        :ref="(el) => setItemRef(item.id, el)"
        role="menuitem"
        :tabindex="getTabIndex(item)"
        :aria-disabled="item.disabled || undefined"
        class="apg-menu-button-item"
        @click="handleItemClick(item)"
        @keydown="(e) => handleMenuKeyDown(e, item)"
        @focus="handleItemFocus(item)"
      >
        {{ item.label }}
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted, nextTick, watch, useId } from 'vue';

export interface MenuItem {
  id: string;
  label: string;
  disabled?: boolean;
}

export interface MenuButtonProps {
  items: MenuItem[];
  label: string;
  defaultOpen?: boolean;
  className?: string;
}

const props = withDefaults(defineProps<MenuButtonProps>(), {
  defaultOpen: false,
  className: '',
});

const emit = defineEmits<{
  itemSelect: [itemId: string];
}>();

defineOptions({
  inheritAttrs: false,
});

// Refs
const containerRef = ref<HTMLDivElement>();
const buttonRef = ref<HTMLButtonElement>();
const menuItemRefs = ref<Record<string, HTMLLIElement>>({});
// Use Vue 3.5+ useId for SSR-safe unique IDs
const instanceId = useId();
const isOpen = ref(props.defaultOpen);
const focusedIndex = ref(-1);
const typeAheadBuffer = ref('');
const typeAheadTimeoutId = ref<number | null>(null);
const typeAheadTimeout = 500;

// Computed
const buttonId = computed(() => `${instanceId}-button`);
const menuId = computed(() => `${instanceId}-menu`);
const availableItems = computed(() => props.items.filter((item) => !item.disabled));

// Map of item id to index in availableItems for O(1) lookup
const availableIndexMap = computed(() => {
  const map = new Map<string, number>();
  availableItems.value.forEach(({ id }, index) => map.set(id, index));
  return map;
});

onUnmounted(() => {
  if (typeAheadTimeoutId.value !== null) {
    clearTimeout(typeAheadTimeoutId.value);
  }
});

// Watch focusedIndex to focus the correct item (also react to availableItems changes)
watch([() => isOpen.value, () => focusedIndex.value, availableItems], async () => {
  if (!isOpen.value || focusedIndex.value < 0) return;

  const targetItem = availableItems.value[focusedIndex.value];
  if (targetItem) {
    await nextTick();
    menuItemRefs.value[targetItem.id]?.focus();
  }
});

// Helper functions
const setItemRef = (id: string, el: unknown) => {
  if (el instanceof HTMLLIElement) {
    menuItemRefs.value[id] = el;
  } else if (el === null) {
    delete menuItemRefs.value[id];
  }
};

const getTabIndex = (item: MenuItem): number => {
  if (item.disabled) return -1;
  const availableIndex = availableIndexMap.value.get(item.id) ?? -1;
  return availableIndex === focusedIndex.value ? 0 : -1;
};

// Menu control
const closeMenu = () => {
  isOpen.value = false;
  focusedIndex.value = -1;
  // Clear type-ahead state
  typeAheadBuffer.value = '';
  if (typeAheadTimeoutId.value !== null) {
    clearTimeout(typeAheadTimeoutId.value);
    typeAheadTimeoutId.value = null;
  }
};

const openMenu = (focusPosition: 'first' | 'last') => {
  if (availableItems.value.length === 0) {
    isOpen.value = true;
    return;
  }

  isOpen.value = true;
  const targetIndex = focusPosition === 'first' ? 0 : availableItems.value.length - 1;
  focusedIndex.value = targetIndex;
};

const toggleMenu = () => {
  if (isOpen.value) {
    closeMenu();
  } else {
    openMenu('first');
  }
};

// Event handlers
const handleItemClick = async (item: MenuItem) => {
  if (item.disabled) return;
  emit('itemSelect', item.id);
  closeMenu();
  await nextTick();
  buttonRef.value?.focus();
};

const handleItemFocus = (item: MenuItem) => {
  if (item.disabled) return;
  const availableIndex = availableIndexMap.value.get(item.id) ?? -1;
  if (availableIndex >= 0) {
    focusedIndex.value = availableIndex;
  }
};

const handleButtonKeyDown = (event: KeyboardEvent) => {
  switch (event.key) {
    case 'Enter':
    case ' ':
      event.preventDefault();
      openMenu('first');
      break;
    case 'ArrowDown':
      event.preventDefault();
      openMenu('first');
      break;
    case 'ArrowUp':
      event.preventDefault();
      openMenu('last');
      break;
  }
};

const handleTypeAhead = (char: string) => {
  const { value: items } = availableItems;
  if (items.length === 0) return;

  if (typeAheadTimeoutId.value !== null) {
    clearTimeout(typeAheadTimeoutId.value);
  }

  typeAheadBuffer.value += char.toLowerCase();

  const buffer = typeAheadBuffer.value;
  const isSameChar = buffer.length > 1 && buffer.split('').every((c) => c === buffer[0]);
  const currentFocusedIndex = focusedIndex.value;
  const itemsLength = items.length;

  let startIndex: number;
  let searchStr: string;

  if (isSameChar) {
    typeAheadBuffer.value = buffer[0];
    searchStr = buffer[0];
    startIndex = currentFocusedIndex >= 0 ? (currentFocusedIndex + 1) % itemsLength : 0;
  } else if (buffer.length === 1) {
    searchStr = buffer;
    startIndex = currentFocusedIndex >= 0 ? (currentFocusedIndex + 1) % itemsLength : 0;
  } else {
    searchStr = buffer;
    startIndex = currentFocusedIndex >= 0 ? currentFocusedIndex : 0;
  }

  for (let i = 0; i < itemsLength; i++) {
    const index = (startIndex + i) % itemsLength;
    const option = items[index];
    if (option.label.toLowerCase().startsWith(searchStr)) {
      focusedIndex.value = index;
      break;
    }
  }

  typeAheadTimeoutId.value = window.setTimeout(() => {
    typeAheadBuffer.value = '';
    typeAheadTimeoutId.value = null;
  }, typeAheadTimeout);
};

const handleMenuKeyDown = async (event: KeyboardEvent, item: MenuItem) => {
  const { value: items } = availableItems;
  const itemsLength = items.length;

  // Guard: no available items
  if (itemsLength === 0) {
    if (event.key === 'Escape') {
      event.preventDefault();
      closeMenu();
      await nextTick();
      buttonRef.value?.focus();
    }
    return;
  }

  const currentIndex = availableIndexMap.value.get(item.id) ?? -1;

  // Guard: disabled item received focus
  if (currentIndex < 0) {
    if (event.key === 'Escape') {
      event.preventDefault();
      closeMenu();
      await nextTick();
      buttonRef.value?.focus();
    }
    return;
  }

  switch (event.key) {
    case 'ArrowDown': {
      event.preventDefault();
      const nextIndex = (currentIndex + 1) % itemsLength;
      focusedIndex.value = nextIndex;
      break;
    }
    case 'ArrowUp': {
      event.preventDefault();
      const prevIndex = currentIndex === 0 ? itemsLength - 1 : currentIndex - 1;
      focusedIndex.value = prevIndex;
      break;
    }
    case 'Home': {
      event.preventDefault();
      focusedIndex.value = 0;
      break;
    }
    case 'End': {
      event.preventDefault();
      focusedIndex.value = itemsLength - 1;
      break;
    }
    case 'Escape': {
      event.preventDefault();
      closeMenu();
      await nextTick();
      buttonRef.value?.focus();
      break;
    }
    case 'Tab': {
      closeMenu();
      break;
    }
    case 'Enter':
    case ' ': {
      event.preventDefault();
      if (!item.disabled) {
        emit('itemSelect', item.id);
        closeMenu();
        await nextTick();
        buttonRef.value?.focus();
      }
      break;
    }
    default: {
      // Type-ahead: single printable character
      const { key, ctrlKey, metaKey, altKey } = event;
      if (key.length === 1 && !ctrlKey && !metaKey && !altKey) {
        event.preventDefault();
        handleTypeAhead(key);
      }
    }
  }
};

// Click outside handler
const handleClickOutside = (event: MouseEvent) => {
  const { value: container } = containerRef;
  if (container && !container.contains(event.target as Node)) {
    closeMenu();
  }
};

watch(
  () => isOpen.value,
  (newIsOpen) => {
    if (newIsOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    } else {
      document.removeEventListener('mousedown', handleClickOutside);
    }
  }
);

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});
</script>
