// src/patterns/button/Button.svelte
<script lang="ts">
  /**
   * Custom Button using role="button"
   *
   * This component demonstrates how to implement a custom button using ARIA.
   * For production use, prefer the native <button> element which provides
   * all accessibility features automatically.
   *
   * @see https://www.w3.org/WAI/ARIA/apg/patterns/button/
   */
  import type { Snippet } from 'svelte';

  interface ButtonProps {
    /** Whether the button is disabled */
    disabled?: boolean;
    /** Click handler */
    onClick?: (event: MouseEvent | KeyboardEvent) => void;
    /** Children content (string for tests, Snippet for slots) */
    children?: string | Snippet<[]>;
    [key: string]: unknown;
  }

  let { disabled = false, onClick, children, ...restProps }: ButtonProps = $props();

  // Track if Space was pressed on this element (for keyup activation)
  let spacePressed = $state(false);

  function handleClick(event: MouseEvent) {
    if (disabled) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }

    onClick?.(event);
  }

  function handleKeyDown(event: KeyboardEvent) {
    // Ignore if composing (IME input) or already handled
    if (event.isComposing || event.defaultPrevented) {
      return;
    }

    if (disabled) {
      return;
    }

    // Space: prevent scroll on keydown, activate on keyup (native button behavior)
    if (event.key === ' ') {
      event.preventDefault();
      spacePressed = true;
      return;
    }

    // Enter: activate on keydown (native button behavior)
    if (event.key === 'Enter') {
      event.preventDefault();
      (event.currentTarget as HTMLElement).click();
    }
  }

  function handleKeyUp(event: KeyboardEvent) {
    // Space: activate on keyup if Space was pressed on this element
    if (event.key === ' ' && spacePressed) {
      spacePressed = false;

      if (disabled) {
        return;
      }

      event.preventDefault();
      (event.currentTarget as HTMLElement).click();
    }
  }
</script>

<span
  {...restProps}
  role="button"
  tabindex={disabled ? -1 : 0}
  aria-disabled={disabled ? 'true' : undefined}
  class="apg-button {restProps.class || ''}"
  onclick={handleClick}
  onkeydown={handleKeyDown}
  onkeyup={handleKeyUp}
  class:undefined={false}
  >{#if typeof children === 'string'}{children}{:else if children}{@render children()}{/if}</span
>

// src/patterns/button/Button.tsx
import { cn } from '@/lib/utils';
import { useCallback, useRef } from 'react';

export interface ButtonProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'onClick'> {
  /** Click handler */
  onClick?: (event: React.MouseEvent | React.KeyboardEvent) => void;
  /** Disabled state */
  disabled?: boolean;
  /** Button content */
  children: React.ReactNode;
}

/**
 * Custom Button using role="button"
 *
 * This component demonstrates how to implement a custom button using ARIA.
 * For production use, prefer the native <button> element which provides
 * all accessibility features automatically.
 *
 * @see https://www.w3.org/WAI/ARIA/apg/patterns/button/
 */
export const Button: React.FC<ButtonProps> = ({
  onClick,
  disabled = false,
  className,
  children,
  ...spanProps
}) => {
  // Track if Space was pressed on this element (for keyup activation)
  const spacePressed = useRef(false);

  const handleClick = useCallback(
    (event: React.MouseEvent<HTMLSpanElement>) => {
      if (disabled) {
        event.preventDefault();
        event.stopPropagation();
        return;
      }

      onClick?.(event);
    },
    [disabled, onClick]
  );

  const handleKeyDown = useCallback(
    (event: React.KeyboardEvent<HTMLSpanElement>) => {
      // Ignore if composing (IME input) or already handled
      if (event.nativeEvent.isComposing || event.defaultPrevented) {
        return;
      }

      if (disabled) {
        return;
      }

      // Space: prevent scroll on keydown, activate on keyup (native button behavior)
      if (event.key === ' ') {
        event.preventDefault();
        spacePressed.current = true;
        return;
      }

      // Enter: activate on keydown (native button behavior)
      if (event.key === 'Enter') {
        event.preventDefault();
        event.currentTarget.click();
      }
    },
    [disabled]
  );

  const handleKeyUp = useCallback(
    (event: React.KeyboardEvent<HTMLSpanElement>) => {
      // Space: activate on keyup if Space was pressed on this element
      if (event.key === ' ' && spacePressed.current) {
        spacePressed.current = false;

        if (disabled) {
          return;
        }

        event.preventDefault();
        event.currentTarget.click();
      }
    },
    [disabled]
  );

  return (
    <span
      {...spanProps}
      role="button"
      tabIndex={disabled ? -1 : 0}
      aria-disabled={disabled ? 'true' : undefined}
      className={cn('apg-button', className)}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      onKeyUp={handleKeyUp}
    >
      {children}
    </span>
  );
};

export default Button;
