// src/patterns/breadcrumb/Breadcrumb.svelte
<script lang="ts">
  /**
   * Breadcrumb component following WAI-ARIA APG pattern
   * @see https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/
   */

  export interface BreadcrumbItem {
    label: string;
    href?: string;
  }

  interface Props {
    items: BreadcrumbItem[];
    ariaLabel?: string;
    class?: string;
  }

  let { items, ariaLabel = 'Breadcrumb', class: className }: Props = $props();

  function getItemKey(item: BreadcrumbItem): string {
    return `${item.href ?? 'current'}-${item.label}`;
  }
</script>

{#if items.length > 0}
  <nav aria-label={ariaLabel} class="apg-breadcrumb {className ?? ''}">
    <ol class="apg-breadcrumb-list">
      {#each items as item, index (getItemKey(item))}
        <li class="apg-breadcrumb-item">
          {#if item.href && index !== items.length - 1}
            <a href={item.href} class="apg-breadcrumb-link">
              {item.label}
            </a>
          {:else}
            <span
              aria-current={index === items.length - 1 ? 'page' : undefined}
              class="apg-breadcrumb-current"
            >
              {item.label}
            </span>
          {/if}
        </li>
      {/each}
    </ol>
  </nav>
{/if}

// src/patterns/breadcrumb/Breadcrumb.vue
<script setup lang="ts">
/**
 * Breadcrumb component following WAI-ARIA APG pattern
 * @see https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/
 */

export interface BreadcrumbItem {
  label: string;
  href?: string;
}

export interface BreadcrumbProps {
  items: BreadcrumbItem[];
  ariaLabel?: string;
  class?: string;
}

const props = withDefaults(defineProps<BreadcrumbProps>(), {
  ariaLabel: 'Breadcrumb',
});

function getItemKey(item: BreadcrumbItem): string {
  return `${item.href ?? 'current'}-${item.label}`;
}
</script>

<template>
  <nav v-if="items.length > 0" :aria-label="ariaLabel" :class="['apg-breadcrumb', props.class]">
    <ol class="apg-breadcrumb-list">
      <li v-for="(item, index) in items" :key="getItemKey(item)" class="apg-breadcrumb-item">
        <a
          v-if="item.href && index !== items.length - 1"
          :href="item.href"
          class="apg-breadcrumb-link"
        >
          {{ item.label }}
        </a>
        <span
          v-else
          :aria-current="index === items.length - 1 ? 'page' : undefined"
          class="apg-breadcrumb-current"
        >
          {{ item.label }}
        </span>
      </li>
    </ol>
  </nav>
</template>
