// src/patterns/feed/KeyboardHints.svelte
<script lang="ts">
  // Keyboard hints component for Feed demo
  // Styles are in src/styles/patterns/feed.css
</script>

<div class="apg-feed-keyboard-hints">
  <div class="apg-feed-keyboard-hints-title">Keyboard Navigation</div>
  <dl class="apg-feed-keyboard-hints-list">
    <div class="apg-feed-keyboard-hint">
      <dt><kbd>Page Down</kbd> / <kbd>Page Up</kbd></dt>
      <dd>Move between articles</dd>
    </div>
    <div class="apg-feed-keyboard-hint">
      <dt><kbd>Ctrl</kbd> + <kbd>End</kbd></dt>
      <dd>Move focus after feed</dd>
    </div>
    <div class="apg-feed-keyboard-hint">
      <dt><kbd>Ctrl</kbd> + <kbd>Home</kbd></dt>
      <dd>Move focus before feed</dd>
    </div>
  </dl>
</div>

// src/patterns/window-splitter/KeyboardHints.vue
<template>
  <div class="apg-window-splitter-keyboard-hints">
    <div class="apg-window-splitter-keyboard-hints-title">Keyboard Navigation</div>
    <dl class="apg-window-splitter-keyboard-hints-list">
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>&larr;</kbd> / <kbd>&rarr;</kbd>
        </dt>
        <dd>Move horizontal splitter</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>&uarr;</kbd> / <kbd>&darr;</kbd>
        </dt>
        <dd>Move vertical splitter</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>Shift</kbd> + Arrow
        </dt>
        <dd>Move by large step</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>Home</kbd> / <kbd>End</kbd>
        </dt>
        <dd>Move to min/max</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>Enter</kbd>
        </dt>
        <dd>Collapse/Expand</dd>
      </div>
    </dl>
  </div>
</template>
