// src/patterns/windowsplitter/WindowSplitterDemo.svelte
<script lang="ts">
  import WindowSplitter from './WindowSplitter.svelte';

  let horizontalPosition = $state(50);
  let verticalPosition = $state(50);
  let horizontalCollapsed = $state(false);
  let verticalCollapsed = $state(false);
  let collapsedPosition = $state(0);
</script>

<div class="apg-window-splitter-demo-wrapper">
  <div class="apg-window-splitter-keyboard-hints">
    <div class="apg-window-splitter-keyboard-hints-title">Keyboard Navigation</div>
    <dl class="apg-window-splitter-keyboard-hints-list">
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>&larr;</kbd> / <kbd>&rarr;</kbd>
        </dt>
        <dd>Move horizontal splitter</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>&uarr;</kbd> / <kbd>&darr;</kbd>
        </dt>
        <dd>Move vertical splitter</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>Shift</kbd> + Arrow
        </dt>
        <dd>Move by large step</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>Home</kbd> / <kbd>End</kbd>
        </dt>
        <dd>Move to min/max</dd>
      </div>
      <div class="apg-window-splitter-keyboard-hint">
        <dt>
          <kbd>Enter</kbd>
        </dt>
        <dd>Collapse/Expand</dd>
      </div>
    </dl>
  </div>

  <!-- Horizontal Splitter Demo -->
  <section class="apg-window-splitter-demo-section">
    <h2 class="apg-window-splitter-demo-title" id="horizontal-demo-label">Horizontal Splitter</h2>
    <div class="apg-window-splitter-demo-info">
      Position: {horizontalPosition}% | Collapsed: {horizontalCollapsed ? 'Yes' : 'No'}
    </div>
    <div
      class="apg-window-splitter-demo-container"
      data-testid="horizontal-demo"
      style="--splitter-position: {horizontalPosition}%"
    >
      <div class="apg-window-splitter-pane" id="horizontal-primary">
        <div class="apg-window-splitter-pane-content">Primary Pane</div>
      </div>
      <WindowSplitter
        primaryPaneId="horizontal-primary"
        secondaryPaneId="horizontal-secondary"
        aria-labelledby="horizontal-demo-label"
        data-testid="horizontal-splitter"
        defaultPosition={50}
        onpositionchange={(pos) => (horizontalPosition = pos)}
        oncollapsedchange={(col) => (horizontalCollapsed = col)}
      />
      <div class="apg-window-splitter-pane" id="horizontal-secondary">
        <div class="apg-window-splitter-pane-content">Secondary Pane</div>
      </div>
    </div>
  </section>

  <!-- Vertical Splitter Demo -->
  <section class="apg-window-splitter-demo-section">
    <h2 class="apg-window-splitter-demo-title" id="vertical-demo-label">Vertical Splitter</h2>
    <div class="apg-window-splitter-demo-info">
      Position: {verticalPosition}% | Collapsed: {verticalCollapsed ? 'Yes' : 'No'}
    </div>
    <div
      class="apg-window-splitter-demo-container apg-window-splitter-demo-container--vertical"
      data-testid="vertical-demo"
      style="--splitter-position: {verticalPosition}%"
    >
      <div class="apg-window-splitter-pane" id="vertical-primary">
        <div class="apg-window-splitter-pane-content">Primary Pane</div>
      </div>
      <WindowSplitter
        primaryPaneId="vertical-primary"
        secondaryPaneId="vertical-secondary"
        orientation="vertical"
        aria-labelledby="vertical-demo-label"
        data-testid="vertical-splitter"
        defaultPosition={50}
        onpositionchange={(pos) => (verticalPosition = pos)}
        oncollapsedchange={(col) => (verticalCollapsed = col)}
      />
      <div class="apg-window-splitter-pane" id="vertical-secondary">
        <div class="apg-window-splitter-pane-content">Secondary Pane</div>
      </div>
    </div>
  </section>

  <!-- Disabled Splitter Demo -->
  <section class="apg-window-splitter-demo-section">
    <h2 class="apg-window-splitter-demo-title" id="disabled-demo-label">Disabled Splitter</h2>
    <div
      class="apg-window-splitter-demo-container"
      data-testid="disabled-demo"
      style="--splitter-position: 30%"
    >
      <div class="apg-window-splitter-pane" id="disabled-primary">
        <div class="apg-window-splitter-pane-content">Primary Pane</div>
      </div>
      <WindowSplitter
        primaryPaneId="disabled-primary"
        secondaryPaneId="disabled-secondary"
        aria-labelledby="disabled-demo-label"
        data-testid="disabled-splitter"
        defaultPosition={30}
        disabled={true}
      />
      <div class="apg-window-splitter-pane" id="disabled-secondary">
        <div class="apg-window-splitter-pane-content">Secondary Pane</div>
      </div>
    </div>
  </section>

  <!-- Readonly Splitter Demo -->
  <section class="apg-window-splitter-demo-section">
    <h2 class="apg-window-splitter-demo-title" id="readonly-demo-label">Readonly Splitter</h2>
    <div
      class="apg-window-splitter-demo-container"
      data-testid="readonly-demo"
      style="--splitter-position: 70%"
    >
      <div class="apg-window-splitter-pane" id="readonly-primary">
        <div class="apg-window-splitter-pane-content">Primary Pane</div>
      </div>
      <WindowSplitter
        primaryPaneId="readonly-primary"
        secondaryPaneId="readonly-secondary"
        aria-labelledby="readonly-demo-label"
        data-testid="readonly-splitter"
        defaultPosition={70}
        readonly={true}
      />
      <div class="apg-window-splitter-pane" id="readonly-secondary">
        <div class="apg-window-splitter-pane-content">Secondary Pane</div>
      </div>
    </div>
  </section>

  <!-- Initially Collapsed Demo -->
  <section class="apg-window-splitter-demo-section">
    <h2 class="apg-window-splitter-demo-title" id="collapsed-demo-label">Initially Collapsed</h2>
    <div
      class="apg-window-splitter-demo-container"
      data-testid="collapsed-demo"
      style="--splitter-position: {collapsedPosition}%"
    >
      <div class="apg-window-splitter-pane" id="collapsed-primary">
        <div class="apg-window-splitter-pane-content">Primary Pane</div>
      </div>
      <WindowSplitter
        primaryPaneId="collapsed-primary"
        secondaryPaneId="collapsed-secondary"
        aria-labelledby="collapsed-demo-label"
        data-testid="collapsed-splitter"
        defaultCollapsed={true}
        expandedPosition={50}
        onpositionchange={(pos) => (collapsedPosition = pos)}
      />
      <div class="apg-window-splitter-pane" id="collapsed-secondary">
        <div class="apg-window-splitter-pane-content">Secondary Pane</div>
      </div>
    </div>
  </section>
</div>

// src/patterns/windowsplitter/WindowSplitterDemo.vue
<template>
  <div class="apg-window-splitter-demo-wrapper">
    <KeyboardHints />

    <!-- Horizontal Splitter Demo -->
    <section class="apg-window-splitter-demo-section">
      <h2 class="apg-window-splitter-demo-title" id="horizontal-demo-label">Horizontal Splitter</h2>
      <div class="apg-window-splitter-demo-info">
        Position: {{ horizontalPosition }}% | Collapsed: {{ horizontalCollapsed ? 'Yes' : 'No' }}
      </div>
      <div
        class="apg-window-splitter-demo-container"
        data-testid="horizontal-demo"
        :style="{ '--splitter-position': `${horizontalPosition}%` }"
      >
        <div class="apg-window-splitter-pane" id="horizontal-primary">
          <div class="apg-window-splitter-pane-content">Primary Pane</div>
        </div>
        <WindowSplitter
          primary-pane-id="horizontal-primary"
          secondary-pane-id="horizontal-secondary"
          aria-labelledby="horizontal-demo-label"
          data-testid="horizontal-splitter"
          :default-position="50"
          @position-change="(pos) => (horizontalPosition = pos)"
          @collapsed-change="(col) => (horizontalCollapsed = col)"
        />
        <div class="apg-window-splitter-pane" id="horizontal-secondary">
          <div class="apg-window-splitter-pane-content">Secondary Pane</div>
        </div>
      </div>
    </section>

    <!-- Vertical Splitter Demo -->
    <section class="apg-window-splitter-demo-section">
      <h2 class="apg-window-splitter-demo-title" id="vertical-demo-label">Vertical Splitter</h2>
      <div class="apg-window-splitter-demo-info">
        Position: {{ verticalPosition }}% | Collapsed: {{ verticalCollapsed ? 'Yes' : 'No' }}
      </div>
      <div
        class="apg-window-splitter-demo-container apg-window-splitter-demo-container--vertical"
        data-testid="vertical-demo"
        :style="{ '--splitter-position': `${verticalPosition}%` }"
      >
        <div class="apg-window-splitter-pane" id="vertical-primary">
          <div class="apg-window-splitter-pane-content">Primary Pane</div>
        </div>
        <WindowSplitter
          primary-pane-id="vertical-primary"
          secondary-pane-id="vertical-secondary"
          orientation="vertical"
          aria-labelledby="vertical-demo-label"
          data-testid="vertical-splitter"
          :default-position="50"
          @position-change="(pos) => (verticalPosition = pos)"
          @collapsed-change="(col) => (verticalCollapsed = col)"
        />
        <div class="apg-window-splitter-pane" id="vertical-secondary">
          <div class="apg-window-splitter-pane-content">Secondary Pane</div>
        </div>
      </div>
    </section>

    <!-- Disabled Splitter Demo -->
    <section class="apg-window-splitter-demo-section">
      <h2 class="apg-window-splitter-demo-title" id="disabled-demo-label">Disabled Splitter</h2>
      <div
        class="apg-window-splitter-demo-container"
        data-testid="disabled-demo"
        style="--splitter-position: 30%"
      >
        <div class="apg-window-splitter-pane" id="disabled-primary">
          <div class="apg-window-splitter-pane-content">Primary Pane</div>
        </div>
        <WindowSplitter
          primary-pane-id="disabled-primary"
          secondary-pane-id="disabled-secondary"
          aria-labelledby="disabled-demo-label"
          data-testid="disabled-splitter"
          :default-position="30"
          disabled
        />
        <div class="apg-window-splitter-pane" id="disabled-secondary">
          <div class="apg-window-splitter-pane-content">Secondary Pane</div>
        </div>
      </div>
    </section>

    <!-- Readonly Splitter Demo -->
    <section class="apg-window-splitter-demo-section">
      <h2 class="apg-window-splitter-demo-title" id="readonly-demo-label">Readonly Splitter</h2>
      <div
        class="apg-window-splitter-demo-container"
        data-testid="readonly-demo"
        style="--splitter-position: 70%"
      >
        <div class="apg-window-splitter-pane" id="readonly-primary">
          <div class="apg-window-splitter-pane-content">Primary Pane</div>
        </div>
        <WindowSplitter
          primary-pane-id="readonly-primary"
          secondary-pane-id="readonly-secondary"
          aria-labelledby="readonly-demo-label"
          data-testid="readonly-splitter"
          :default-position="70"
          readonly
        />
        <div class="apg-window-splitter-pane" id="readonly-secondary">
          <div class="apg-window-splitter-pane-content">Secondary Pane</div>
        </div>
      </div>
    </section>

    <!-- Initially Collapsed Demo -->
    <section class="apg-window-splitter-demo-section">
      <h2 class="apg-window-splitter-demo-title" id="collapsed-demo-label">Initially Collapsed</h2>
      <div
        class="apg-window-splitter-demo-container"
        data-testid="collapsed-demo"
        :style="{ '--splitter-position': `${collapsedPosition}%` }"
      >
        <div class="apg-window-splitter-pane" id="collapsed-primary">
          <div class="apg-window-splitter-pane-content">Primary Pane</div>
        </div>
        <WindowSplitter
          primary-pane-id="collapsed-primary"
          secondary-pane-id="collapsed-secondary"
          aria-labelledby="collapsed-demo-label"
          data-testid="collapsed-splitter"
          default-collapsed
          :expanded-position="50"
          @position-change="(pos) => (collapsedPosition = pos)"
        />
        <div class="apg-window-splitter-pane" id="collapsed-secondary">
          <div class="apg-window-splitter-pane-content">Secondary Pane</div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import WindowSplitter from './WindowSplitter.vue';
import KeyboardHints from './KeyboardHints.vue';

const horizontalPosition = ref(50);
const verticalPosition = ref(50);
const horizontalCollapsed = ref(false);
const verticalCollapsed = ref(false);
const collapsedPosition = ref(0);
</script>
