// site/src/components/patterns/button/ToggleButton.tsx
import { useCallback, useState } from "react";

export interface ToggleButtonProps
  extends Omit<
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    "onClick" | "type" | "aria-pressed"
  > {
  /** Initial pressed state */
  initialPressed?: boolean;
  /** Button label text */
  children: React.ReactNode;
  /** Callback fired when toggle state changes */
  onToggle?: (pressed: boolean) => void;
}

export const ToggleButton: React.FC<ToggleButtonProps> = ({
  initialPressed = false,
  children,
  onToggle,
  className = "",
  ...buttonProps
}) => {
  const [pressed, setPressed] = useState(initialPressed);

  const handleClick = useCallback(() => {
    setPressed(!pressed);
    onToggle?.(!pressed);
  }, [pressed, onToggle]);

  // Build CSS classes
  const stateClass = pressed
    ? "apg-toggle-button--pressed"
    : "apg-toggle-button--not-pressed";

  return (
    <button
      type="button"
      {...buttonProps}
      className={`apg-toggle-button ${stateClass} ${className}`.trim()}
      aria-pressed={pressed}
      onClick={handleClick}
    >
      <span className="apg-toggle-button-content">{children}</span>
      <span
        className={`apg-toggle-indicator ${
          pressed
            ? "apg-toggle-indicator--pressed"
            : "apg-toggle-indicator--not-pressed"
        }`}
        aria-hidden="true"
      >
        {pressed ? "●" : "○"}
      </span>
    </button>
  );
};

export default ToggleButton;

// site/src/components/patterns/button/ToggleButton.vue
<template>
  <button
    type="button"
    :class="buttonClasses"
    :aria-pressed="pressed"
    v-bind="$attrs"
    @click="handleClick"
  >
    <span class="apg-toggle-button-content">
      <slot />
    </span>
    <span
      :class="indicatorClasses"
      aria-hidden="true"
    >
      {{ pressed ? '●' : '○' }}
    </span>
  </button>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

// Inherit all HTML button attributes
defineOptions({
  inheritAttrs: false
})

export interface ToggleButtonProps {
  /** Initial pressed state */
  initialPressed?: boolean;
  /** Callback fired when toggle state changes */
  onToggle?: (pressed: boolean) => void;
}

const props = withDefaults(defineProps<ToggleButtonProps>(), {
  initialPressed: false,
  onToggle: undefined
})

const emit = defineEmits<{
  toggle: [pressed: boolean]
}>()

const pressed = ref(props.initialPressed)

const handleClick = () => {
  const newPressed = !pressed.value
  pressed.value = newPressed

  // Call onToggle prop if provided (for React compatibility)
  props.onToggle?.(newPressed)
  // Emit Vue event
  emit('toggle', newPressed)
}

// Build CSS classes
const buttonClasses = computed(() => {
  const stateClass = pressed.value
    ? 'apg-toggle-button--pressed'
    : 'apg-toggle-button--not-pressed'

  return `apg-toggle-button ${stateClass}`.trim()
})

const indicatorClasses = computed(() => {
  const stateClass = pressed.value
    ? 'apg-toggle-indicator--pressed'
    : 'apg-toggle-indicator--not-pressed'

  return `apg-toggle-indicator ${stateClass}`
})
</script>
