// src/patterns/feed/KeyboardHintsJa.svelte
<script lang="ts">
  // Japanese keyboard hints component for Feed demo
  // Styles are in src/styles/patterns/feed.css
</script>

<div class="apg-feed-keyboard-hints">
  <div class="apg-feed-keyboard-hints-title">キーボード操作</div>
  <dl class="apg-feed-keyboard-hints-list">
    <div class="apg-feed-keyboard-hint">
      <dt><kbd>Page Down</kbd> / <kbd>Page Up</kbd></dt>
      <dd>記事間を移動</dd>
    </div>
    <div class="apg-feed-keyboard-hint">
      <dt><kbd>Ctrl</kbd> + <kbd>End</kbd></dt>
      <dd>フィードの後にフォーカス移動</dd>
    </div>
    <div class="apg-feed-keyboard-hint">
      <dt><kbd>Ctrl</kbd> + <kbd>Home</kbd></dt>
      <dd>フィードの前にフォーカス移動</dd>
    </div>
  </dl>
</div>

// src/patterns/feed/KeyboardHintsJa.vue
<template>
  <div class="apg-feed-keyboard-hints">
    <div class="apg-feed-keyboard-hints-title">キーボード操作</div>
    <dl class="apg-feed-keyboard-hints-list">
      <div class="apg-feed-keyboard-hint">
        <dt><kbd>Page Down</kbd> / <kbd>Page Up</kbd></dt>
        <dd>記事間を移動</dd>
      </div>
      <div class="apg-feed-keyboard-hint">
        <dt><kbd>Ctrl</kbd> + <kbd>End</kbd></dt>
        <dd>フィードの後にフォーカス移動</dd>
      </div>
      <div class="apg-feed-keyboard-hint">
        <dt><kbd>Ctrl</kbd> + <kbd>Home</kbd></dt>
        <dd>フィードの前にフォーカス移動</dd>
      </div>
    </dl>
  </div>
</template>

<script setup lang="ts">
// Japanese keyboard hints component for Feed demo
// Styles are in src/styles/patterns/feed.css
</script>
