// demos/svelte/src/components/ToggleButton.svelte
<script lang="ts">
  // Custom props
  export let initialPressed = false;
  export let onToggle: (pressed: boolean) => void = () => {};

  // State
  let pressed = initialPressed;

  // Event handlers
  function handleClick() {
    pressed = !pressed;
    onToggle(pressed);
  }

  function handleKeyUp(event: KeyboardEvent) {
    // Handle Space and Enter keys according to APG specification
    if (event.key === " " || event.key === "Enter") {
      event.preventDefault(); // Prevent default behavior (scrolling for space)
      handleClick();
    }
  }

  // Reactive classes
  $: stateClass = pressed
    ? "apg-toggle-button--pressed"
    : "apg-toggle-button--not-pressed";
  $: indicatorClass = pressed
    ? "apg-toggle-indicator--pressed"
    : "apg-toggle-indicator--not-pressed";
  $: buttonClasses = `apg-toggle-button ${stateClass}`.trim();
</script>

<button
  type="button"
  class={buttonClasses}
  aria-pressed={pressed}
  {...$$restProps}
  on:click={handleClick}
  on:keyup={handleKeyUp}
>
  <span class="apg-toggle-button-content">
    <slot />
  </span>
  <span class="apg-toggle-indicator {indicatorClass}" aria-hidden="true">
    {pressed ? "●" : "○"}
  </span>
</button>

// demos/vue/src/components/ToggleButton.vue
<template>
  <button
    type="button"
    :class="buttonClasses"
    :aria-pressed="pressed"
    v-bind="$attrs"
    @click="handleClick"
    @keyup="handleKeyUp"
  >
    <span class="apg-toggle-button-content">
      <slot />
    </span>
    <span
      :class="indicatorClasses"
      aria-hidden="true"
    >
      {{ pressed ? '●' : '○' }}
    </span>
  </button>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

// Inherit all HTML button attributes
defineOptions({
  inheritAttrs: false
})

export interface ToggleButtonProps {
  /** Initial pressed state */
  initialPressed?: boolean;
  /** Callback fired when toggle state changes */
  onToggle?: (pressed: boolean) => void;
}

const props = withDefaults(defineProps<ToggleButtonProps>(), {
  initialPressed: false,
  onToggle: undefined
})

const emit = defineEmits<{
  toggle: [pressed: boolean]
}>()

const pressed = ref(props.initialPressed)

const handleClick = () => {
  const newPressed = !pressed.value
  pressed.value = newPressed
  
  // Call onToggle prop if provided (for React compatibility)
  props.onToggle?.(newPressed)
  // Emit Vue event
  emit('toggle', newPressed)
}

const handleKeyUp = (event: KeyboardEvent) => {
  // Handle Space and Enter keys according to APG specification
  if (event.key === ' ' || event.key === 'Enter') {
    event.preventDefault() // Prevent default behavior (scrolling for space)
    handleClick()
  }
}

// Build CSS classes
const buttonClasses = computed(() => {
  const stateClass = pressed.value
    ? 'apg-toggle-button--pressed'
    : 'apg-toggle-button--not-pressed'
  
  return `apg-toggle-button ${stateClass}`.trim()
})

const indicatorClasses = computed(() => {
  const stateClass = pressed.value
    ? 'apg-toggle-indicator--pressed'
    : 'apg-toggle-indicator--not-pressed'
  
  return `apg-toggle-indicator ${stateClass}`
})
</script>
