// src/patterns/toolbar/ToolbarButton.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getToolbarContext } from './toolbar-context.svelte';

  interface ToolbarButtonProps {
    children?: Snippet<[]>;
    disabled?: boolean;
    class?: string;
    onclick?: (event: MouseEvent) => void;
    [key: string]: unknown;
  }

  let {
    children,
    disabled = false,
    class: className = '',
    onclick,
    ...restProps
  }: ToolbarButtonProps = $props();

  // Verify we're inside a Toolbar
  const context = getToolbarContext();
  if (!context) {
    console.warn('ToolbarButton must be used within a Toolbar');
  }
</script>

<button
  type="button"
  class="apg-toolbar-button {className}"
  {disabled}
  {onclick}
  {...restProps}
>
  {#if children}
    {@render children()}
  {/if}
</button>

// src/patterns/toolbar/ToolbarButton.vue
<script lang="ts">
export interface ToolbarButtonProps {
  /** Whether the button is disabled */
  disabled?: boolean;
}
</script>

<template>
  <button type="button" class="apg-toolbar-button" :disabled="disabled" v-bind="$attrs">
    <slot />
  </button>
</template>

<script setup lang="ts">
import { inject } from 'vue';
import { ToolbarContextKey } from './toolbar-context';

defineOptions({
  inheritAttrs: false,
});

withDefaults(
  defineProps<{
    /** Whether the button is disabled */
    disabled?: boolean;
  }>(),
  {
    disabled: false,
  }
);

// Verify we're inside a Toolbar
const context = inject(ToolbarContextKey);
if (!context) {
  console.warn('ToolbarButton must be used within a Toolbar');
}
</script>
