// src/patterns/toolbar/VerticalToolbarDemo.svelte
<script lang="ts">
  import Toolbar from './Toolbar.svelte';
  import ToolbarButton from './ToolbarButton.svelte';
  import ToolbarSeparator from './ToolbarSeparator.svelte';
</script>

<Toolbar orientation="vertical" aria-label="Actions">
  <ToolbarButton>New</ToolbarButton>
  <ToolbarButton>Open</ToolbarButton>
  <ToolbarButton>Save</ToolbarButton>
  <ToolbarSeparator />
  <ToolbarButton>Print</ToolbarButton>
</Toolbar>

// src/patterns/toolbar/VerticalToolbarDemo.vue
<script setup lang="ts">
import Toolbar from './Toolbar.vue';
import ToolbarButton from './ToolbarButton.vue';
import ToolbarSeparator from './ToolbarSeparator.vue';
</script>

<template>
  <Toolbar orientation="vertical" aria-label="Actions">
    <ToolbarButton>New</ToolbarButton>
    <ToolbarButton>Open</ToolbarButton>
    <ToolbarButton>Save</ToolbarButton>
    <ToolbarSeparator />
    <ToolbarButton>Print</ToolbarButton>
  </Toolbar>
</template>
