// src/patterns/meter/Meter.tsx
import { clsx } from 'clsx';

// Label: one of these required (exclusive)
type LabelProps =
  | { label: string; 'aria-label'?: never; 'aria-labelledby'?: never }
  | { label?: never; 'aria-label': string; 'aria-labelledby'?: never }
  | { label?: never; 'aria-label'?: never; 'aria-labelledby': string };

// ValueText: exclusive with format
type ValueTextProps =
  | { valueText: string; format?: never }
  | { valueText?: never; format?: string }
  | { valueText?: never; format?: never };

type MeterBaseProps = {
  value: number;
  min?: number;
  max?: number;
  clamp?: boolean;
  showValue?: boolean;
  id?: string;
  className?: string;
  tabIndex?: number;
  'aria-describedby'?: string;
  'data-testid'?: string;
};

export type MeterProps = MeterBaseProps & LabelProps & ValueTextProps;

const clampNumber = (value: number, min: number, max: number, shouldClamp: boolean): number => {
  if (!Number.isFinite(value) || !Number.isFinite(min) || !Number.isFinite(max)) {
    return value;
  }
  return shouldClamp ? Math.min(max, Math.max(min, value)) : value;
};

const calculatePercentage = (value: number, min: number, max: number): number => {
  if (max === min) return 0;
  return ((value - min) / (max - min)) * 100;
};

// Format value helper
const formatValueText = (
  value: number,
  formatStr: string | undefined,
  min: number,
  max: number
): string => {
  if (!formatStr) return String(value);
  return formatStr
    .replace('{value}', String(value))
    .replace('{min}', String(min))
    .replace('{max}', String(max));
};

export const Meter: React.FC<MeterProps> = ({
  value,
  min = 0,
  max = 100,
  clamp = true,
  showValue = true,
  label,
  valueText,
  format,
  className,
  ...rest
}) => {
  const normalizedValue = clampNumber(value, min, max, clamp);
  const percentage = calculatePercentage(normalizedValue, min, max);

  // Determine aria-valuetext
  const ariaValueText =
    valueText ?? (format ? formatValueText(normalizedValue, format, min, max) : undefined);

  // Determine display text (valueText takes priority, then format, then raw value)
  const displayText = valueText ? valueText : formatValueText(normalizedValue, format, min, max);

  return (
    <div
      role="meter"
      aria-valuenow={normalizedValue}
      aria-valuemin={min}
      aria-valuemax={max}
      aria-valuetext={ariaValueText}
      aria-label={label ?? rest['aria-label']}
      aria-labelledby={rest['aria-labelledby']}
      className={clsx('apg-meter', className)}
      id={rest.id}
      tabIndex={rest.tabIndex}
      aria-describedby={rest['aria-describedby']}
      data-testid={rest['data-testid']}
    >
      {label && (
        <span className="apg-meter-label" aria-hidden="true">
          {label}
        </span>
      )}
      <div className="apg-meter-track" aria-hidden="true">
        <div
          className="apg-meter-fill"
          style={{ width: `${Math.max(0, Math.min(100, percentage))}%` }}
        />
      </div>
      {showValue && (
        <span className="apg-meter-value" aria-hidden="true">
          {displayText}
        </span>
      )}
    </div>
  );
};

// src/patterns/meter/Meter.svelte
<script lang="ts">
  interface MeterProps {
    value: number;
    min?: number;
    max?: number;
    clamp?: boolean;
    showValue?: boolean;
    label?: string;
    valueText?: string;
    /** Format pattern for dynamic value display (e.g., "{value}%", "{value} of {max}") */
    format?: string;
    [key: string]: unknown;
  }

  let {
    value,
    min = 0,
    max = 100,
    clamp = true,
    showValue = true,
    label,
    valueText,
    format,
    ...restProps
  }: MeterProps = $props();

  function clampNumber(val: number, minVal: number, maxVal: number, shouldClamp: boolean): number {
    if (!Number.isFinite(val) || !Number.isFinite(minVal) || !Number.isFinite(maxVal)) {
      return val;
    }
    return shouldClamp ? Math.min(maxVal, Math.max(minVal, val)) : val;
  }

  // Format value helper
  function formatValueText(
    val: number,
    formatStr: string | undefined,
    minVal: number,
    maxVal: number
  ): string {
    if (!formatStr) return String(val);
    return formatStr
      .replace('{value}', String(val))
      .replace('{min}', String(minVal))
      .replace('{max}', String(maxVal));
  }

  const normalizedValue = $derived(clampNumber(value, min, max, clamp));

  const percentage = $derived(() => {
    if (max === min) return 0;
    const pct = ((normalizedValue - min) / (max - min)) * 100;
    return Math.max(0, Math.min(100, pct));
  });

  const ariaValueText = $derived(
    valueText ?? (format ? formatValueText(normalizedValue, format, min, max) : undefined)
  );

  const displayText = $derived(
    valueText ? valueText : formatValueText(normalizedValue, format, min, max)
  );
</script>

<div
  role="meter"
  aria-valuenow={normalizedValue}
  aria-valuemin={min}
  aria-valuemax={max}
  aria-valuetext={ariaValueText}
  aria-label={label || restProps['aria-label']}
  aria-labelledby={restProps['aria-labelledby']}
  aria-describedby={restProps['aria-describedby']}
  class="apg-meter {restProps.class || ''}"
  id={restProps.id}
  tabindex={restProps.tabindex}
  data-testid={restProps['data-testid']}
>
  {#if label}
    <span class="apg-meter-label" aria-hidden="true">
      {label}
    </span>
  {/if}
  <div class="apg-meter-track" aria-hidden="true">
    <div class="apg-meter-fill" style="width: {percentage()}%"></div>
  </div>
  {#if showValue}
    <span class="apg-meter-value" aria-hidden="true">
      {displayText}
    </span>
  {/if}
</div>
