// src/patterns/checkbox/Checkbox.tsx
import { cn } from '@/lib/utils';
import { useCallback, useEffect, useRef, useState } from 'react';

export interface CheckboxProps extends Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  'type' | 'onChange'
> {
  /** Initial checked state */
  initialChecked?: boolean;
  /** Indeterminate (mixed) state */
  indeterminate?: boolean;
  /** Callback when checked state changes */
  onCheckedChange?: (checked: boolean) => void;
  /** Test ID for wrapper element */
  'data-testid'?: string;
}

export const Checkbox: React.FC<CheckboxProps> = ({
  initialChecked = false,
  indeterminate = false,
  onCheckedChange,
  className,
  disabled,
  'data-testid': dataTestId,
  ...inputProps
}) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const [checked, setChecked] = useState(initialChecked);
  const [isIndeterminate, setIsIndeterminate] = useState(indeterminate);

  // Update indeterminate property on the input element
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = isIndeterminate;
    }
  }, [isIndeterminate]);

  // Sync with prop changes
  useEffect(() => {
    setIsIndeterminate(indeterminate);
  }, [indeterminate]);

  const handleChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const newChecked = event.target.checked;
      setChecked(newChecked);
      setIsIndeterminate(false);
      onCheckedChange?.(newChecked);
    },
    [onCheckedChange]
  );

  return (
    <span className={cn('apg-checkbox', className)} data-testid={dataTestId}>
      <input
        ref={inputRef}
        type="checkbox"
        className="apg-checkbox-input"
        checked={checked}
        disabled={disabled}
        onChange={handleChange}
        {...inputProps}
      />
      <span className="apg-checkbox-control" aria-hidden="true">
        <span className="apg-checkbox-icon apg-checkbox-icon--check">
          <svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path
              d="M10 3L4.5 8.5L2 6"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </span>
        <span className="apg-checkbox-icon apg-checkbox-icon--indeterminate">
          <svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M2.5 6H9.5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
          </svg>
        </span>
      </span>
    </span>
  );
};

export default Checkbox;

// src/patterns/checkbox/Checkbox.svelte
<script lang="ts">
  import { untrack } from 'svelte';

  interface CheckboxProps {
    initialChecked?: boolean;
    indeterminate?: boolean;
    disabled?: boolean;
    name?: string;
    value?: string;
    onCheckedChange?: (checked: boolean) => void;
    [key: string]: unknown;
  }

  let {
    initialChecked = false,
    indeterminate: indeterminateProp = false,
    disabled = false,
    name,
    value,
    onCheckedChange = () => {},
    ...restProps
  }: CheckboxProps = $props();

  let checked = $state(untrack(() => initialChecked));
  let isIndeterminate = $state(untrack(() => indeterminateProp));
  let inputRef: HTMLInputElement | undefined = $state();

  // Update indeterminate property when ref or state changes
  $effect(() => {
    if (inputRef) {
      inputRef.indeterminate = isIndeterminate;
    }
  });

  // Sync with prop changes
  $effect(() => {
    isIndeterminate = indeterminateProp;
  });

  function handleChange(event: Event) {
    const target = event.target as HTMLInputElement;
    checked = target.checked;
    isIndeterminate = false;
    onCheckedChange(checked);
  }
</script>

<span class="apg-checkbox {restProps.class || ''}" data-testid={restProps['data-testid']}>
  <input
    bind:this={inputRef}
    type="checkbox"
    class="apg-checkbox-input"
    {checked}
    {disabled}
    {name}
    {value}
    onchange={handleChange}
    {...restProps}
    data-testid={undefined}
  />
  <span class="apg-checkbox-control" aria-hidden="true">
    <span class="apg-checkbox-icon apg-checkbox-icon--check">
      <svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M10 3L4.5 8.5L2 6"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </span>
    <span class="apg-checkbox-icon apg-checkbox-icon--indeterminate">
      <svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M2.5 6H9.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" />
      </svg>
    </span>
  </span>
</span>
